local M = {}

M.config = {
	config_file = "",
	title = " MyPack ",
	catalog_url = "https://raw.githubusercontent.com/rockerBOO/awesome-neovim/main/README.md",
	cache_file = vim.fn.stdpath("data") .. "/pack_handle/awesome-neovim.json",
}

local state = {
	buf = nil,
	win = nil,
	plugins = {},
	catalog_buf = nil,
	catalog_win = nil,
	catalog = nil,
	catalog_query = "",
	catalog_tab = 1,
	catalog_row = 1,
	catalog_rows = {},
	catalog_refreshing = false,
}

local pack_handle_ns = vim.api.nvim_create_namespace("pack_handle_ns")

local function notify(message, level)
	vim.notify(message, level or vim.log.levels.INFO, { title = "MyPack" })
end

local function is_valid_window()
	return state.win and vim.api.nvim_win_is_valid(state.win)
end

local function is_valid_buffer()
	return state.buf and vim.api.nvim_buf_is_valid(state.buf)
end

local function is_valid_catalog_window()
	return state.catalog_win and vim.api.nvim_win_is_valid(state.catalog_win)
end

local function is_valid_catalog_buffer()
	return state.catalog_buf and vim.api.nvim_buf_is_valid(state.catalog_buf)
end

local function set_highlights()
	local highlights = {
		PackHandleTitle = { link = "Title" },
		PackHandleTab = { link = "Comment" },
		PackHandleTabActive = { link = "Visual" },
		PackHandleRule = { link = "NonText" },
		PackHandleName = { link = "Identifier" },
		PackHandleStatus = { link = "DiagnosticInfo" },
		PackHandleMeta = { link = "Comment" },
		PackHandleHint = { link = "Comment" },
		PackHandleSearch = { link = "Search" },
	}
	for name, options in pairs(highlights) do
		vim.api.nvim_set_hl(0, name, vim.tbl_extend("force", { default = true }, options))
	end
end

local function floating_dimensions(width_ratio, height_ratio, min_width, min_height)
	local width = math.min(110, math.max(min_width, math.floor(vim.o.columns * width_ratio)))
	local height = math.min(30, math.max(min_height, math.floor(vim.o.lines * height_ratio)))
	return width, height
end

local function escape_lua_string(value)
	return value:gsub("\\", "\\\\"):gsub('"', '\\"')
end

-- Return the closing brace for a table beginning at `open_at`. This intentionally
-- supports the normal, simple vim.pack.add({ ... }) form generated by this plugin.
local function matching_brace(text, open_at)
	local depth = 0
	local quote
	local escaped = false
	for i = open_at, #text do
		local char = text:sub(i, i)
		if quote then
			if escaped then
				escaped = false
			elseif char == "\\" then
				escaped = true
			elseif char == quote then
				quote = nil
			end
		elseif char == '"' or char == "'" then
			quote = char
		elseif char == "{" then
			depth = depth + 1
		elseif char == "}" then
			depth = depth - 1
			if depth == 0 then
				return i
			end
		end
	end
end

local function config_contents()
	local file = M.config.config_file
	if vim.fn.filereadable(file) == 0 then
		return ""
	end
	local lines, err = vim.fn.readfile(file)
	if not lines then
		return nil, err
	end
	return table.concat(lines, "\n")
end

local function write_config(contents)
	local file = M.config.config_file
	local parent = vim.fs.dirname(file)
	if vim.fn.isdirectory(parent) == 0 then
		vim.fn.mkdir(parent, "p")
	end
	local lines = vim.split(contents, "\n", { plain = true })
	-- writefile() terminates every line. Do not turn a final newline in
	-- `contents` into an additional blank line on disk.
	if lines[#lines] == "" then
		table.remove(lines)
	end
	local ok, err = pcall(vim.fn.writefile, lines, file)
	if not ok then
		return nil, err
	end
	return true
end

local function add_to_config(url)
	local contents, err = config_contents()
	if not contents then
		return nil, err
	end
	local quoted = '"' .. escape_lua_string(url) .. '"'
	if contents:find(quoted, 1, true) then
		return nil, "URL is already present in " .. M.config.config_file
	end

	local start_at = contents:find("vim.pack.add%s*%(%s*{")
	if start_at then
		local open_at = contents:find("{", start_at, true)
		local close_at = matching_brace(contents, open_at)
		if not close_at then
			return nil, "Could not find the end of vim.pack.add table"
		end
		local entries = contents:sub(open_at + 1, close_at - 1)
		-- A trailing comma is optional in Lua, but it is required before we
		-- append another entry. Add it after the final token when the existing
		-- table's last entry omitted one.
		if not entries:match(",%s*$") then
			entries = entries:gsub("(%S)(%s*)$", "%1,%2", 1)
		end
		contents = contents:sub(1, open_at) .. entries .. "  " .. quoted .. ",\n" .. contents:sub(close_at)
	elseif contents == "" then
		contents = "vim.pack.add({\n  " .. quoted .. ",\n})\n"
	else
		contents = contents .. "\n\nvim.pack.add({\n  " .. quoted .. ",\n})\n"
	end
	return write_config(contents)
end

local function remove_from_config(url)
	if not url then
		return true
	end
	local contents, err = config_contents()
	if not contents then
		return nil, err
	end

	-- Only remove URLs from vim.pack.add tables.  Looking through the entire file
	-- could otherwise remove an unrelated string (for example, a comment or a
	-- variable holding the same URL).
	local search_at = 1
	while true do
		local start_at = contents:find("vim.pack.add%s*%(%s*{", search_at)
		if not start_at then
			return true
		end
		local open_at = contents:find("{", start_at, true)
		local close_at = matching_brace(contents, open_at)
		if not close_at then
			return nil, "Could not find the end of vim.pack.add table"
		end

		local entries = contents:sub(open_at + 1, close_at - 1)
		local double_quoted = ('"' .. escape_lua_string(url) .. '"'):gsub("(%W)", "%%%1")
		local single_quoted = ("'" .. url:gsub("\\", "\\\\"):gsub("'", "\\'") .. "'"):gsub("(%W)", "%%%1")
		local entry_start, entry_end = entries:find(double_quoted)
		if not entry_start then
			entry_start, entry_end = entries:find(single_quoted)
		end

		if entry_start then
			local before = entries:sub(1, entry_start - 1)
			local after = entries:sub(entry_end + 1)
			-- vim.pack also accepts a spec such as
			-- { src = "https://example.com/owner/plugin", name = "plugin" }.
			-- In that case the entire spec must go, not just its URL value.
			local spec_open = before:match(".*(){")
			if spec_open then
				local spec_close = matching_brace(entries, spec_open)
				if spec_close and spec_close >= entry_end then
					entry_start, entry_end = spec_open, spec_close
					before = entries:sub(1, entry_start - 1)
					after = entries:sub(entry_end + 1)
				end
			end

			-- Prefer consuming the following comma; for a final entry consume the
			-- preceding comma instead. Both keep the remaining Lua table valid for
			-- multiline and one-line vim.pack.add calls.
			local remove_start, remove_end
			local next_comma = after:find("^%s*,")
			if next_comma then
				remove_start = entry_start
				remove_end = entry_end + next_comma
			else
				local previous_comma = before:match("(),%s*$")
				if previous_comma then
					remove_start = previous_comma
					remove_end = entry_end
				else
					remove_start = entry_start
					remove_end = entry_end
				end
			end

			-- When an entry occupies its own line, remove that line's leading
			-- newline as well.  Otherwise deleting the first or a middle entry
			-- leaves its indentation behind as an empty line in the table.
			local line_start = before:match("()\n[ \t]*$")
			if line_start then
				remove_start = line_start
			end
			entries = entries:sub(1, remove_start - 1) .. entries:sub(remove_end + 1)
			-- A table whose only entry was removed should not retain a blank line.
			if entries:match("^%s*$") then
				entries = ""
			end
			contents = contents:sub(1, open_at) .. entries .. contents:sub(close_at)
			return write_config(contents)
		end

		search_at = close_at + 1
	end
end

local function cache_catalog(catalog)
	local cache_file = M.config.cache_file
	local parent = vim.fs.dirname(cache_file)
	if vim.fn.isdirectory(parent) == 0 then
		vim.fn.mkdir(parent, "p")
	end
	local ok, encoded = pcall(vim.json.encode, catalog)
	if not ok then
		return nil, encoded
	end
	local temporary_file = cache_file .. ".tmp"
	local written, err = pcall(vim.fn.writefile, { encoded }, temporary_file)
	if not written then
		return nil, err
	end
	if vim.fn.rename(temporary_file, cache_file) ~= 0 then
		return nil, "Could not replace catalog cache"
	end
	return true
end

local function load_catalog()
	if state.catalog then
		return state.catalog
	end
	local cache_file = M.config.cache_file
	if vim.fn.filereadable(cache_file) == 0 then
		return nil, "No catalog cache yet. Press r to download it."
	end
	local lines, err = vim.fn.readfile(cache_file)
	if not lines then
		return nil, err
	end
	local ok, catalog = pcall(vim.json.decode, table.concat(lines, "\n"))
	if not ok or type(catalog) ~= "table" or type(catalog.plugins) ~= "table" then
		return nil, "Catalog cache is invalid. Press r to download it again."
	end
	state.catalog = catalog
	return catalog
end

local function parse_catalog(markdown)
	local plugins, seen = {}, {}
	local category = "Other"
	for line in markdown:gmatch("[^\r\n]+") do
		local heading = line:match("^##+%s+(.+)%s*$")
		if heading then
			category = heading:gsub("%s*%[.-%]", "")
		else
			local repo, url, description = line:match("^%s*[%*%-]%s+%[([^%]]+)%]%(([^)]+)%)%s*%-%s+(.+)$")
			if repo then
				repo = repo:gsub("#.*$", "")
				local github_repo = url:match("^https?://github%.com/([^/]+/[^/#]+)")
				if github_repo then
					url = "https://github.com/" .. github_repo
				end
			else
				repo, description = line:match("^%s*[%*%-]%s+([%w%._%-]+/[%w%._%-]+)[^%s]*%s*%-%s+(.+)$")
				if repo then
					url = "https://github.com/" .. repo
				end
			end
			if repo and not seen[repo] then
				seen[repo] = true
				table.insert(plugins, {
					repo = repo,
					url = url,
					description = description:gsub("%s+$", ""),
					category = category,
				})
			end
		end
	end
	table.sort(plugins, function(a, b)
		return a.repo:lower() < b.repo:lower()
	end)
	return plugins
end

local function catalog_categories(catalog)
	local categories, seen = { "All" }, { All = true }
	for _, plugin in ipairs(catalog.plugins) do
		if not seen[plugin.category] then
			seen[plugin.category] = true
			table.insert(categories, plugin.category)
		end
	end
	table.sort(categories, function(a, b)
		if a == "All" then
			return true
		end
		if b == "All" then
			return false
		end
		return a:lower() < b:lower()
	end)
	return categories
end

local function catalog_results(catalog)
	local categories = catalog_categories(catalog)
	state.catalog_tab = math.min(state.catalog_tab, #categories)
	local category = categories[state.catalog_tab]
	local query = state.catalog_query:lower()
	local results = {}
	for _, plugin in ipairs(catalog.plugins) do
		local haystack = (plugin.repo .. " " .. plugin.description .. " " .. plugin.category):lower()
		if (category == "All" or plugin.category == category) and (query == "" or haystack:find(query, 1, true)) then
			table.insert(results, plugin)
		end
	end
	return categories, results
end

local function truncate(text, width)
	if vim.fn.strdisplaywidth(text) <= width then
		return text
	end
	return vim.fn.strcharpart(text, 0, math.max(1, width - 1)) .. "…"
end

local function render_catalog()
	if not is_valid_catalog_buffer() then
		return
	end
	local catalog, error_message = load_catalog()
	local width = vim.api.nvim_win_get_width(state.catalog_win)
	local lines, highlights = {}, {}
	local function add(line, group)
		table.insert(lines, line)
		if group then
			highlights[#lines] = group
		end
	end

	add(" Plugin Discovery ", "PackHandleTitle")
	if not catalog then
		add("", nil)
		add(error_message, "PackHandleMeta")
		add("", nil)
		add("Press r to fetch the Awesome Neovim catalog.", "PackHandleHint")
		add(string.rep("─", width), "PackHandleRule")
		add("r refresh catalog   q close", "PackHandleHint")
		state.catalog_rows = {}
	else
		local categories, results = catalog_results(catalog)
		-- Keep the selected tab in view.  The catalog has more categories than a
		-- normal floating window can show, so a simple left-to-right truncation
		-- would make the active category disappear after navigating far enough.
		local function tab_label(index)
			local name = categories[index]
			return index == state.catalog_tab and ("[ " .. name .. " ]") or ("  " .. name .. "  ")
		end
		local available = math.max(12, width - 4) -- room for left/right overflow marks
		local selected = tab_label(state.catalog_tab)
		if vim.fn.strdisplaywidth(selected) > available then
			selected = "[ " .. truncate(categories[state.catalog_tab], available - 4) .. " ]"
		end
		local tabs, used = { selected }, vim.fn.strdisplaywidth(selected)
		local left, right = state.catalog_tab - 1, state.catalog_tab + 1
		local prefer_left = true
		while left >= 1 or right <= #categories do
			local index
			if prefer_left and left >= 1 then
				index, left = left, left - 1
			elseif right <= #categories then
				index, right = right, right + 1
			elseif left >= 1 then
				index, left = left, left - 1
			end
			prefer_left = not prefer_left
			local label = tab_label(index)
			local label_width = vim.fn.strdisplaywidth(label) + vim.fn.strdisplaywidth("│")
			if used + label_width <= available then
				if index < state.catalog_tab then
					table.insert(tabs, 1, label)
				else
					table.insert(tabs, label)
				end
				used = used + label_width
			elseif index < state.catalog_tab then
				left = 0
			else
				right = #categories + 1
			end
		end
		local tab_text = table.concat(tabs, "│")
		if left >= 1 then
			tab_text = "‹ " .. tab_text
		end
		if right <= #categories then
			tab_text = tab_text .. " ›"
		end
		add(truncate(tab_text, width), "PackHandleTab")
		add(string.rep("─", width), "PackHandleRule")
		local search = state.catalog_query == "" and "Search: /" or "Search: " .. state.catalog_query
		add(truncate(search .. string.format("   %d results", #results), width), "PackHandleSearch")
		add("", nil)
		state.catalog_rows = results
		for _, plugin in ipairs(results) do
			local repo_width = math.min(34, math.max(22, math.floor(width * 0.36)))
			local text = string.format(
				"  %-" .. repo_width .. "s %s",
				truncate(plugin.repo, repo_width),
				truncate(plugin.description, width - repo_width - 3)
			)
			add(text, "PackHandleName")
		end
		if #results == 0 then
			add("  No plugins match this category and search.", "PackHandleMeta")
		end
		add("", nil)
		add(string.rep("─", width), "PackHandleRule")
		add("h/l tabs   / search   Enter add   r refresh catalog   q close", "PackHandleHint")
	end

	vim.bo[state.catalog_buf].modifiable = true
	vim.api.nvim_buf_set_lines(state.catalog_buf, 0, -1, false, lines)
	vim.api.nvim_buf_clear_namespace(state.catalog_buf, pack_handle_ns, 0, -1)
	for line, group in pairs(highlights) do
		-- vim.api.nvim_buf_add_highlight(state.catalog_buf, -1, group, line - 1, 0, -1)
		vim.api.nvim_buf_set_extmark(state.catalog_buf, pack_handle_ns, line - 1, 0, {
			hl_group = group,
			end_col = #lines[line],
		})
	end
	vim.bo[state.catalog_buf].modifiable = false
end

local function refresh_catalog()
	if state.catalog_refreshing then
		return
	end
	state.catalog_refreshing = true
	notify("Refreshing Awesome Neovim catalog…")
	local started, start_error = pcall(
		vim.system,
		{ "curl", "--fail", "--location", "--silent", "--show-error", M.config.catalog_url },
		{ text = true },
		function(result)
			vim.schedule(function()
				state.catalog_refreshing = false
				if result.code ~= 0 then
					notify(
						"Could not refresh catalog: " .. (result.stderr ~= "" and result.stderr or "curl failed"),
						vim.log.levels.ERROR
					)
					render_catalog()
					return
				end
				local plugins = parse_catalog(result.stdout)
				if #plugins == 0 then
					notify("Could not parse any plugins from the catalog", vim.log.levels.ERROR)
					render_catalog()
					return
				end
				local catalog = { version = 1, updated_at = os.time(), plugins = plugins }
				local ok, err = cache_catalog(catalog)
				if not ok then
					notify("Catalog downloaded but could not be cached: " .. err, vim.log.levels.ERROR)
					return
				end
				state.catalog = catalog
				state.catalog_tab = 1
				notify(string.format("Catalog refreshed: %d plugins", #plugins))
				render_catalog()
			end)
		end
	)
	if not started then
		state.catalog_refreshing = false
		notify("Could not start catalog refresh: " .. start_error, vim.log.levels.ERROR)
		render_catalog()
	end
end

local function plugin_rows()
	local ok, plugins = pcall(vim.pack.get)
	if not ok then
		notify("Unable to read vim.pack plugins: " .. plugins, vim.log.levels.ERROR)
		return {}
	end
	table.sort(plugins, function(a, b)
		return a.spec.name < b.spec.name
	end)
	return plugins
end

local function add_catalog_selection()
	local line = vim.api.nvim_win_get_cursor(state.catalog_win)[1]
	-- Results begin after the title, tab bar, rule, search bar, and spacer.
	local plugin = state.catalog_rows[line - 5]
	if not plugin then
		return
	end
	local config_ok, config_err = add_to_config(plugin.url)
	if not config_ok then
		notify(config_err, vim.log.levels.ERROR)
		return
	end
	local ok, err = pcall(vim.pack.add, { plugin.url }, { confirm = false })
	if not ok then
		notify("Saved " .. plugin.repo .. " to config, but install failed: " .. err, vim.log.levels.ERROR)
		return
	end
	notify("Added " .. plugin.repo)
	M.refresh()
end

local function set_catalog_query()
	vim.ui.input({ prompt = "Search Awesome Neovim: ", default = state.catalog_query }, function(query)
		if query == nil then
			return
		end
		state.catalog_query = vim.trim(query)
		render_catalog()
	end)
end

local function change_catalog_tab(offset)
	local catalog = load_catalog()
	if not catalog then
		return
	end
	local categories = catalog_categories(catalog)
	state.catalog_tab = ((state.catalog_tab - 1 + offset) % #categories) + 1
	render_catalog()
end

function M.open_catalog()
	if is_valid_catalog_window() then
		vim.api.nvim_set_current_win(state.catalog_win)
		render_catalog()
		return
	end
	set_highlights()
	state.catalog_buf = vim.api.nvim_create_buf(false, true)
	vim.bo[state.catalog_buf].bufhidden = "wipe"
	vim.bo[state.catalog_buf].buftype = "nofile"
	vim.bo[state.catalog_buf].swapfile = false
	vim.bo[state.catalog_buf].filetype = "packhandle-catalog"
	local width, height = floating_dimensions(0.78, 0.72, 72, 16)
	state.catalog_win = vim.api.nvim_open_win(state.catalog_buf, true, {
		relative = "editor",
		style = "minimal",
		border = "rounded",
		title = " MyPack · Discover ",
		title_pos = "center",
		width = width,
		height = height,
		row = math.floor((vim.o.lines - height) / 2),
		col = math.floor((vim.o.columns - width) / 2),
	})
	for key, callback in pairs({
		["<CR>"] = add_catalog_selection,
		["/"] = set_catalog_query,
		s = set_catalog_query,
		h = function()
			change_catalog_tab(-1)
		end,
		l = function()
			change_catalog_tab(1)
		end,
		["<Tab>"] = function()
			change_catalog_tab(1)
		end,
		["<S-Tab>"] = function()
			change_catalog_tab(-1)
		end,
		r = refresh_catalog,
		q = function()
			vim.api.nvim_win_close(state.catalog_win, true)
		end,
	}) do
		vim.keymap.set("n", key, callback, { buffer = state.catalog_buf, nowait = true, silent = true })
	end
	vim.api.nvim_create_autocmd("BufWipeout", {
		buffer = state.catalog_buf,
		once = true,
		callback = function()
			state.catalog_buf, state.catalog_win = nil, nil
		end,
	})
	render_catalog()
end

function M.refresh()
	if not is_valid_buffer() then
		return
	end
	state.plugins = plugin_rows()
	local width = vim.api.nvim_win_get_width(state.win)
	local lines = { " MyPack ", string.rep("─", width) }
	for _, plugin in ipairs(state.plugins) do
		local status = plugin.active and "active" or "inactive"
		table.insert(
			lines,
			string.format("  %-24s %-9s %s", plugin.spec.name, status, truncate(plugin.spec.src, width - 38))
		)
	end
	if #state.plugins == 0 then
		table.insert(lines, "  No plugins managed by vim.pack.")
	end
	table.insert(lines, "")
	table.insert(lines, string.rep("─", width))
	table.insert(lines, "a add URL   s discover   d delete   r refresh list   q close")
	vim.bo[state.buf].modifiable = true
	vim.api.nvim_buf_set_lines(state.buf, 0, -1, false, lines)
	vim.api.nvim_buf_clear_namespace(state.buf, pack_handle_ns, 0, -1)
	-- vim.api.nvim_buf_add_highlight(state.buf, -1, "PackHandleTitle", 0, 0, -1)
	vim.api.nvim_buf_set_extmark(state.buf, pack_handle_ns, 0, 0, {
		hl_group = "PackHandleTitle",
		end_col = #lines[1],
	})
	-- vim.api.nvim_buf_add_highlight(state.buf, -1, "PackHandleRule", 1, 0, -1)

	vim.api.nvim_buf_set_extmark(state.buf, pack_handle_ns, 1, 0, {
		hl_group = "PackHandleRule",
		end_col = #lines[2],
	})
	for index, plugin in ipairs(state.plugins) do
		local line = index + 1
		-- vim.api.nvim_buf_add_highlight(state.buf, -1, "PackHandleName", line, 2, 26)
		vim.api.nvim_buf_set_extmark(state.buf, pack_handle_ns, line, 2, {
			hl_group = "PackHandleName",
			end_col = 26,
            -- strict = false,
		})

		-- vim.api.nvim_buf_add_highlight(
		-- 	state.buf,
		-- 	-1,
		-- 	plugin.active and "PackHandleStatus" or "PackHandleMeta",
		-- 	line,
		-- 	27,
		-- 	36
		-- )

		vim.api.nvim_buf_set_extmark(state.buf, pack_handle_ns, line, 27, {
			hl_group = plugin.active and "PackHandleStatus" or "PackHandleMeta",
			end_col = 36,
		})
	end
	-- vim.api.nvim_buf_add_highlight(state.buf, -1, "PackHandleRule", #lines - 2, 0, -1)

	vim.api.nvim_buf_set_extmark(state.buf, pack_handle_ns, #lines - 2, 0, {
		hl_group = "PackHandleRule",
		end_col = #lines[#lines - 1],
	})
	-- vim.api.nvim_buf_add_highlight(state.buf, -1, "PackHandleHint", #lines - 1, 0, -1)

	vim.api.nvim_buf_set_extmark(state.buf, pack_handle_ns, #lines - 1, 0, {
		hl_group = "PackHandleHint",
		end_col = #lines[#lines],
	})
	vim.bo[state.buf].modifiable = false
end

local function selected_plugin()
	local line = vim.api.nvim_win_get_cursor(state.win)[1]
	return state.plugins[line - 2]
end

function M.delete_selected()
	local plugin = selected_plugin()
	if not plugin then
		notify("Move the cursor to a plugin first", vim.log.levels.WARN)
		return
	end
	local answer = vim.fn.confirm("Delete " .. plugin.spec.name .. "?", "&Delete\n&Cancel", 2)
	if answer ~= 1 then
		return
	end
	local ok, err = pcall(vim.pack.del, { plugin.spec.name }, { force = true })
	if not ok then
		notify("Could not delete " .. plugin.spec.name .. ": " .. err, vim.log.levels.ERROR)
		return
	end
	local config_ok, config_err = remove_from_config(plugin.spec.src)
	if not config_ok then
		notify("Plugin deleted, but config was not updated: " .. config_err, vim.log.levels.WARN)
	else
		notify("Deleted " .. plugin.spec.name)
	end
	M.refresh()
end

function M.add()
	vim.ui.input({ prompt = "Plugin URL: " }, function(url)
		if not url or url == "" then
			return
		end
		url = vim.trim(url)
		if not url:match("^[%w+.-]+://") and not url:match("^[%w_.-]+@[%w_.-]+:") then
			notify("Enter a Git URL (for example https://github.com/owner/repo)", vim.log.levels.WARN)
			return
		end
		local config_ok, config_err = add_to_config(url)
		if not config_ok then
			notify(config_err, vim.log.levels.ERROR)
			return
		end
		local ok, err = pcall(vim.pack.add, { url }, { confirm = false })
		if not ok then
			notify("Saved URL to config, but install failed: " .. err, vim.log.levels.ERROR)
			return
		end
		notify("Added " .. url)
		M.refresh()
	end)
end

function M.open()
	if M.config.config_file == "" then
		notify("You forget to call setup!", vim.log.levels.ERROR)
		return
	end
	if is_valid_window() then
		vim.api.nvim_set_current_win(state.win)
		M.refresh()
		return
	end
	set_highlights()
	state.buf = vim.api.nvim_create_buf(false, true)
	vim.bo[state.buf].bufhidden = "wipe"
	vim.bo[state.buf].buftype = "nofile"
	vim.bo[state.buf].swapfile = false
	vim.bo[state.buf].filetype = "mypack"
	local width, height = floating_dimensions(0.72, 0.62, 60, 10)
	state.win = vim.api.nvim_open_win(state.buf, true, {
		relative = "editor",
		style = "minimal",
		border = "rounded",
		title = " MyPack ",
		title_pos = "center",
		width = width,
		height = height,
		row = math.floor((vim.o.lines - height) / 2),
		col = math.floor((vim.o.columns - width) / 2),
	})
	for key, callback in pairs({
		a = M.add,
		s = M.open_catalog,
		d = M.delete_selected,
		r = M.refresh,
		q = function()
			vim.api.nvim_win_close(state.win, true)
		end,
	}) do
		vim.keymap.set("n", key, callback, { buffer = state.buf, nowait = true, silent = true })
	end
	vim.api.nvim_create_autocmd("BufWipeout", {
		buffer = state.buf,
		once = true,
		callback = function()
			state.buf, state.win = nil, nil
		end,
	})
	M.refresh()
end

function M.setup(opts)
	M.config = vim.tbl_deep_extend("force", M.config, opts or {})
end

return M
